version: '3'
services:
  nginx:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
  
  frontend:
    image: node:latest
    environment:
      - VIRTUAL_HOST=${HOST}
    volumes:
      - /srv/frontend/src:/app
    working_dir: /app
    entrypoint: ["yarn", "start"]
    expose:
      - 3000
    restart: always
  
  spring-api:
    build: /srv/backend/
    environment:
      - VIRTUAL_HOST=api.${HOST}
    restart: always

  webserver:
    build: /srv/server/
    environment:
      - VIRTUAL_HOST=back.${HOST}
    volumes:
      - /srv/server/app:/app
    restart: always